### ISSUE TITLE
 No video found mass grabber

### ISSUE THREAD

**Issue by michaelroevievictoria** [Joel2B/WP-Script-API#7]
Have you ever encounter this ? 
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/115077715/225286774-fce5242e-801d-4a07-b430-97acf79670a0.png">
I accidentally  update my wp-script core , then my site is automatically update, then all my theme are now in buy now button,

I tried to restore my back up and now its fixed but my wp-script-mass grabber is not working properly 

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/115077715/225287094-d8b966c7-117e-42d5-a5f6-dadc1af2ba90.png">

**Comment by Joel2B** [comment]
i just realized and the "license key" that i use to get the data, was banned.

i don't have another key so unfortunately this project is over.

i restored the data from a few months ago and seems to be working for now, 
although i don't think they will last long, since the sites are constantly changing their code.
